# Copyright 2022 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

name: Code Test Coverage Workflow

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
      - develop

jobs:
  code-test-coverage:
    name: Code test coverage job

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Go environment explicitly
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true

      - name: Generate full test coverage report using go-acc
        run: make test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage.txt
          flags: defra-tests
          name: codecov-umbrella
          verbose: true
          # path_to_write_report: ./coverage/codecov_report.txt
          # directory: ./coverage/reports/
