# Copyright 2022 Democratized Data Foundation
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.txt.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0, included in the file
# licenses/APL.txt.

name: Start Binary Workflow

on:
  pull_request:

  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - master
      - develop

jobs:
  start-binary:
    name: Start binary job

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code into the directory
        uses: actions/checkout@v3

      - name: Setup Go environment explicitly
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          check-latest: true

      - name: Build modules
        run: make deps:modules

      - name: Build binary
        run: make build

      - name: Attempt to start binary
        run: |
          ./build/defradb start &
          sleep 5

      - name: Check if binary is still running
        run: |
          FOUND=$(pgrep -c "defradb");
          echo "Process(es) we found = [${FOUND}]";
          if [[ ${FOUND} == 0 ]]; then
            echo "DefraDB start command failed.";
            exit 1;
          else
            echo "DefraDB running.";
          fi
